{% set name = "types-polib" %}
{% set version = "1.1.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-polib-{{ version }}.tar.gz
  sha256: 2597925c8bac2042c9b4091663e1b84fd023a4828f530bbfbeb5f2be1fc77f67

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/polib-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for polib
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
